name: CI / Frontend

on:
  push:
  pull_request:

jobs:
  type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: cd client && yarn install && cd ../
      - name: Type check
        run: cd client && yarn run flow && cd ../
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: cd client && yarn install && cd ../
      - name: Run tests
        run: cd client && yarn test && cd ../
